services:
  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: npx json-server --watch src/data/db.json --port 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
